travis:
  secure:
    BINSTAR_TOKEN: DPwCZ4o2/q5ZwlRcHP/OGoRMxskDtuQQnQHlHXe62I+z3ghsHSAxaMblb8p+npdOoWJvjXfFNmoeiRhrSYEbprvEtYGM0xG8LihFCUEmeQtH6rWKyr2zBUXKure4nxLxmrvz+a1HRaYg90SKpbXSbQHGSd07npCRbv7G/HTL4rya01t+XhPvZweQwlJc78UH8BpXEFAajwOBiirr5Xveq/if3AIv0ngnP601oN44nhx8aK1QQLdmoLWl8v2F/42d/UV5R2P93y+Qh0ODqH5F6H8n2c/rkh/4Nv9MCxj/C3et0GtRLj24vCtXWVwPHnedV7g+7D2Vs6GwmoLxtxiGq7Ce0r3cy//LMD24r0ys/zSFmhNR1sJMOEXZazWL3eDm+DdM9ueCBQpXgOlcnKBz6U77w2WZVGC8J3ndWPMsUx6S32AjVvz6jm6Lpk6KukypxxGwr++4Um/ewRab8ShHzyf65XUtAKXdwDzPEPLWZsmir84gAdMU9Lqkfga2VxwUXj3DgtlZmHkyBIUYAjdkVxB0jeLwnUQdT7DCWuivDMZyz0DiM+ZsZU9U516T6iRD0gN/NXPQDMLZQUKwuAoZPvX7a4af5qfGuDiS7aAsOTxTOKcZF3yZ4YXtk3xkK5Pp4+onlj7q6kg49cpMt7EWadLb6gV9Ur3qhrgu613D+Xw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
