travis:
  secure:
    BINSTAR_TOKEN: Cv8KZSYjpBT4hxZohcVG7MLlM/fFPZaFfLwDC+hNQeXLo0atM/nuoflBjffbHZTmALhLGLEEI111DRmB8qCZaJFS8jPAGDC4il+bYQKZoSxm3PRYjRPEyDUn1SWfkraRWhOBdf79addsm8gmuPPbDOQL5mJVdo+xKVJQNx8xVCVmPI/6lvux/JvJ5KFGMjzlpTwVjkRxNJoYU2nh+2hY9IOMvOBjK2zgjGgSqsFtlRHid+5aCkVBrftZNeYLZyRwK62IKUDm+UyNoNhvDAZuKbGJtF/QRovfWQqcKKR246Ee3mS9Mhd838EUtdaoQL5XQcPsayYle0Q76MCp93oAxoZucAEYQ5Zdf6iv52hS/CvV05rETuLaj4QHYGUfTjdsxPZN2dby9K2V8PO267QJe7TaUJsqlhDYkyavEmTFy43bQkiXVnLpEuR7HMsmc7edCqX0Eqr1u2C9m48e1sq7rCE4NCOWDgFoEQxBmZLJfySu+Cec2UlAL2tKbREde+sUuow3hmq41/4gZ5yO259J1kyllNjmVpnB1Xk8EcUjCKow2T0yzQXYG8ofZ9EzLFRKguE8CTWeXR3ELNrWtyKshJ9EJug3/qc95At8uv6G5cYtqxJl9ZjrdyfantNsibZI26RPgYfoZmp0x8vbK2LmkRbuOLsuCGJlP4tqon42CL8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
